module.exports.carbrand = [
    {
        image:"/carbrandlogo/aston-202943.svg",
        title:"aston martin"
    },
    {
        image:"/carbrandlogo/acura-202938.svg",
        title:"acura"
    },
    {
        image:"/carbrandlogo/audi-0111.svg",
        title:"audi"
    },
    {
        image:"/carbrandlogo/bentley-202732.svg",
        title:"bently"
    },
    {
        image:"/carbrandlogo/bmw-202746.svg",
        title:"BMW"
    },
    {
        image:"/carbrandlogo/ferrari-202771.svg",
        title:"ferari"
    },
    {
        image:"/carbrandlogo/ford-202764.svg",
        title:"ford"
    },
    {
        image:"/carbrandlogo/gmc-202770.svg",
        title:"gmc"
    },
    {
        image:"/carbrandlogo/hendrick-202772.svg",
        title:"hendrick"
    },
    {
        image:"/carbrandlogo/honda-202779.svg",
        title:"honda"
    },
    {
        image:"/carbrandlogo/isuzu-202820.svg",
        title:"isuzu"
    },
    {
        image:"/carbrandlogo/jaguar-202813.svg",
        title:"jaguar"
    },
    {
        image:"/carbrandlogo/kia-202830.svg",
        title:"kia"
    },
    {
        image:"/carbrandlogo/lexus-202829.svg",
        title:"lexus"
    },
    {
        image:"/carbrandlogo/mercedes-202839.svg",
        title:"mercedes"
    },
    {
        image:"/carbrandlogo/mg-202848.svg",
        title:"mg"
    },
    {
        image:"/carbrandlogo/nissan-202859.svg",
        title:"nissan"
    },
    {
        image:"/carbrandlogo/porsche-202875.svg",
        title:"porsche"
    },
    {
        image:"/carbrandlogo/subaru-202908.svg",
        title:"subaru"
    },
    {
        image:"/carbrandlogo/toyota-202914.svg",
        title:"toyota"
    },
    {
        image:"/carbrandlogo/volvo-202923.svg",
        title:"volvo"
    }
]

module.exports.motorcyclebrand = [
    {
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Aprilia-logo.svg/1200px-Aprilia-logo.svg.png",
        title:"aprilia"
    },
    {
        image:"https://logosvector.net/wp-content/uploads/2012/10/bajaj-logo-vector.png",
        title:"bajaj"
    },
    {
        image:"/carbrandlogo/bmw-202746.svg",
        title:"bmw"
    },
    {
        image:"https://gpxthailand.com/wp-content/uploads/2021/12/cropped-logo@2x.png",
        title:"gpx"
    },
    {
        image:"http://www.hanwaythailand.com/wp-content/uploads/2019/02/hanway-logo.png",
        title:"hanway"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Harley_davidson_logo.jpg/1243px-Harley_davidson_logo.jpg",
        title:"Harley davidson"
    },
    {
        image:"https://seekvectorlogo.com/wp-content/uploads/2017/12/honda-motorcycles-vector-logo-small.png",
        title:"honda"
    },
    {
        image:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Kawasaki-logo.svg/1024px-Kawasaki-logo.svg.png",
        title:"kawasaki"
    },
    {
        image:"https://seeklogo.com/images/S/suzuki-logo-5311518DD9-seeklogo.com.png",
        title:"suzuki"
    },
    {
        image:"https://inwfile.com/s-fu/gv5g1v.jpg",
        title:"yamaha"
    }
]